import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>Header</header>
        <div>Hello from layout</div>
        <div style={{ width: "100%", height: "300px", position: "relative" }}>
          <Image
            src="/forest.jpg"
            alt="House"
            layout="fill"  // image fills the parent container
            objectFit="cover" // or "cover"
          />
        </div>
        {children}
        <footer>Footer</footer>
      </body>
    </html>
  );
}
